#!/bin/bash

echo "Compiling in ${OSTYPE}"

if [ $# == "0" ] || [ "$1" == "all" ]
then 
    echo "Compiling all the agents"
    javac -classpath "lib/jade.jar:lib/commons-codec-1.3.jar" -d classes src/agents/*/*.java src/messages/*.java src/launcher/*.java
else
    echo "Compiling agent $1"
    javac -classpath lib/jade.jar -d classes src/agents/"$1"/*.java
fi
