#!/bin/bash

companySimulation="java -cp lib/jade.jar:classes jade.Boot -gui"

for i in `seq 2 $1`
do
    companySimulation="$companySimulation company${i}:agents.CompanyAgent.CompanyAgent"
done

$companySimulation