#!/bin/bash

companySimulation="java -cp lib/jade.jar:classes jade.Boot -gui -agents "

for i in `seq 1 $1`
do
    agents="${agents}company${i}:agents.CompanyAgent.CompanyAgent;"
done

agents="${agents::-1}"

$companySimulation $agents