#!/bin/bash

# Start the economy
startEconomy="java -cp lib/jade.jar:classes jade.Boot -gui -agents eco:agents.EconomyAgent.EconomyAgent"

#============================#

# Start the companies

# Run at least 1 company
if [ $# -eq 0 ]
  then
    numberOfCompanies=1
  else
    numberOfCompanies=$1
fi

echo "Starting $numberOfCompanies companies"
for i in `seq 1 $numberOfCompanies`
do
  startEconomy="$startEconomy;company${i}:agents.CompanyAgent.CompanyAgent"
done

if [ $# -ge 2 ] && [ $2 == "sniffer" ]
  then
    startEconomy="$startEconomy;sniffer:jade.tools.sniffer.Sniffer"
fi

$startEconomy